
# This is a basic workflow to help you get started with Actions

name: CI/CD MARKETING

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [marketing]
  pull_request:
    branches: [none]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    name: "Deploy to marketing Frontend"
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/server.key
          chmod 600 ~/.ssh/server.key
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/server.key
            StrictHostKeyChecking no
            Port $PORT
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          PORT: ${{ secrets.PORT }}

      - name: Deploying into server
        run: |
          ssh server 'cd /home/admin/web/marketing.ditinex.com/public_html && git reset --hard && git pull origin marketing'
          ssh server 'cd /home/admin/web/marketing.ditinex.com/public_html && npm install && npm run build && pm2 restart marketing'
      - run: echo "🎉 Deployed successfully."
